name: '🔧 Chore'
description: '설정, 패키지, 구조 등 기타 작업을 진행합니다.'
title: '[CHORE] '
labels:
  - '🔧 CHORE'

body:
  - type: textarea
    id: summary
    attributes:
      label: '🔧 변경 내용'
      placeholder: |
        - [ ] 변경 사항 1
        - [ ] 변경 사항 2
      value: |
        - [ ]
    validations:
      required: true
