name: '📝 Docs'
description: '문서 작성 및 수정을 진행합니다.'
title: '[DOCS] '
labels:
  - '📝 DOCS'

body:
  - type: textarea
    id: summary
    attributes:
      label: '📝 문서 작업'
      value: |
        - [ ]
    validations:
      required: true
