name: '♻️ Refactor'
description: '기존 코드의 구조를 개선합니다.'
title: '[REFACTOR] '
labels:
  - '♻️ REFACTOR'

body:
  - type: textarea
    id: summary
    attributes:
      label: '♻️ 개선 내용'
      value: |
        - [ ]
    validations:
      required: true
